#!/usr/bin/fish
set -l GITCHECKPATHS ~/Repos/ ~/.config
set -g NUM_FAILED 0

if [ ! -d ~/.local/git-checks ]
  mkdir -p ~/.local/git-checks
end

for path in $GITCHECKPATHS
  for repo in (find $path -type d -name .git)
    cd (dirname $repo)
    echo "Updating repository $(pwd)..."
    set -l pull_output (git pull 2>&1)
    if [ $status -ne 0 ]
      set -g NUM_FAILED ($NUM_FAILED + 1)
      echo "$(pwd) failed to update. Reason: $pull_output" >> ~/.local/git-checks/git_checks.log
    end
  end
end

if [ $NUM_FAILED -eq 0 ]
  echo "  "
else
  echo "  $NUM_FAILED"
end

